# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futebola', '0009_jogo_epoca'),
    ]

    operations = [
        migrations.AddField(
            model_name='epoca',
            name='epoca_num',
            field=models.IntegerField(default=0),
        ),
    ]
