# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futebola', '0010_epoca_epoca_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epoca',
            old_name='epoca_num',
            new_name='numeracao_epoca',
        ),
    ]
