# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futebola', '0012_auto_20180102_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epoca',
            name='numeracao_epoca',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
