# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-10 12:25
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futebola', '0014_auto_20180326_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalizacao',
            fields=[
                ('penalizacao_id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(default=datetime.date.today)),
                ('valor', models.IntegerField(default=0)),
                ('motivo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='epoca',
            options={'ordering': ['-numeracao_epoca']},
        ),
        migrations.AlterModelOptions(
            name='jogador',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='jogo',
            options={'ordering': ['-data']},
        ),
        migrations.AlterField(
            model_name='jogador',
            name='ataque',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='defesa',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='experiencia',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='finalizacao',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='forca',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='garra',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='guarda_redes',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='passe',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='posicionamento',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='remates_longe',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='resistencia',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='tecnica',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='velocidade',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='penalizacao',
            name='epoca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='futebola.Epoca'),
        ),
        migrations.AddField(
            model_name='penalizacao',
            name='jogador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futebola.Jogador'),
        ),
    ]
