# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-23 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futebola', '0015_auto_20191010_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='foto',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
