# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 12:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("futebola", "0007_auto_20171124_1438"),
    ]

    operations = [
        migrations.CreateModel(
            name="Epoca",
            fields=[
                ("epoca_id", models.AutoField(primary_key=True, serialize=False)),
                ("inicio", models.DateField(default=datetime.date.today)),
                ("fim", models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
