# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("futebola", "0008_epoca"),
    ]

    operations = [
        migrations.AddField(
            model_name="jogo",
            name="epoca",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="futebola.Epoca",
            ),
        ),
    ]
