# Generated by Django 4.0 on 2021-12-15 15:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("futebola", "0016_jogador_foto"),
    ]

    operations = [
        migrations.AddField(
            model_name="penalizacao",
            name="game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="futebola.jogo",
            ),
        ),
        migrations.AlterField(
            model_name="jogador",
            name="foto",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="penalizacao",
            name="epoca",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                to="futebola.epoca",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Bonus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            (
                                "most_assists_in_game",
                                "Mais assistências num jogo pela sua equipa",
                            )
                        ],
                        max_length=100,
                    ),
                ),
                ("value", models.IntegerField(default=0)),
                ("date", models.DateField(default=datetime.date.today)),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="futebola.jogo",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="futebola.jogador",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="futebola.epoca"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Bonuses",
            },
        ),
    ]
